/** Generated from Open Design v0.23.1 design-systems DESIGN.md files (Apache-2.0, see NOTICE). */
export interface CatalogEntry {
  readonly id: string;
  readonly name: string;
  readonly category: string;
  readonly summary: string;
  readonly swatches: readonly string[];
}

export const CATALOG_INDEX: readonly CatalogEntry[] = [
  {
    id: "apple",
    name: "Apple",
    category: "Media & Consumer",
    summary: "Consumer electronics. Premium white space, SF Pro, cinematic imagery.",
    swatches: ["#000000", "#F5F5F7", "#0071E3", "#0066CC"],
  },
  {
    id: "linear-app",
    name: "Linear",
    category: "Productivity & SaaS",
    summary: "Project management. Ultra-minimal, precise, purple accent.",
    swatches: ["#08090A", "#F7F8F8", "#5E6AD2", "#7170FF"],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Fintech & Crypto",
    summary: "Payment infrastructure. Signature purple gradients, weight-300 elegance.",
    swatches: ["#FFFFFF", "#061B31", "#533AFD", "#EA2261"],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Developer Tools",
    summary: "Frontend deployment. Black and white precision, Geist font.",
    swatches: ["#FFFFFF", "#171717", "#FF5B4F", "#DE1D8D"],
  },
  {
    id: "notion",
    name: "Notion",
    category: "Productivity & SaaS",
    summary: "All-in-one workspace. Warm minimalism, serif headings, soft surfaces.",
    swatches: ["#FFFFFF", "#F6F5F4", "#31302E", "#615D59"],
  },
  {
    id: "airbnb",
    name: "Airbnb",
    category: "E-Commerce & Retail",
    summary: "Travel marketplace. Warm coral accent, photography-driven, rounded UI.",
    swatches: ["#FF385C", "#222222", "#92174D", "#460479"],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Backend & Data",
    summary: "Open-source Firebase alternative. Dark emerald theme, code-first.",
    swatches: ["#0F0F0F", "#171717", "#3ECF8E", "#00C573"],
  },
  {
    id: "figma",
    name: "Figma",
    category: "Design & Creative",
    summary: "Collaborative design tool. Vibrant multi-color, playful yet professional.",
    swatches: ["#000000", "#FFFFFF"],
  },
  {
    id: "claude",
    name: "Claude (Anthropic)",
    category: "AI & LLM",
    summary: "Anthropic's AI assistant. Warm terracotta accent, clean editorial layout.",
    swatches: ["#F5F4ED", "#C96442", "#5E5D59", "#87867F"],
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "Developer Tools",
    summary: "AI-first code editor. Sleek dark interface, gradient accents.",
    swatches: ["#F2F1ED", "#26251E", "#E6E5E0", "#EBEAE5"],
  },
  {
    id: "raycast",
    name: "Raycast",
    category: "Developer Tools",
    summary: "Productivity launcher. Sleek dark chrome, vibrant gradient accents.",
    swatches: ["#07080A", "#FF6363", "#FFFFFF", "#55B3FF"],
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "Media & Consumer",
    summary: "Music streaming. Vibrant green on dark, bold type, album-art-driven.",
    swatches: ["#121212", "#181818", "#1F1F1F", "#1ED760"],
  },
  {
    id: "github",
    name: "GitHub",
    category: "Developer Tools",
    summary:
      "Code-forward platform. Functional density, blue-on-white precision, Primer foundations.",
    swatches: ["#FFFFFF", "#0D1117", "#0969DA", "#1A7F37"],
  },
  {
    id: "discord",
    name: "Discord",
    category: "Productivity & SaaS",
    summary: "Voice / chat platform. Deep blurple, dark-first surfaces, playful accent moments.",
    swatches: ["#313338", "#1E1F22", "#5865F2", "#2B2D31"],
  },
  {
    id: "x-ai",
    name: "xAI",
    category: "AI & LLM",
    summary: "Elon Musk's AI lab. Stark monochrome, futuristic minimalism.",
    swatches: ["#1F2228", "#FFFFFF", "#000000"],
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "AI & LLM",
    summary:
      "Calm, near-monochrome system anchored in deep teal-black with generous white space and editorial typography.",
    swatches: ["#FFFFFF", "#0D0D0D", "#E5E5E5", "#1A1A1A"],
  },
  {
    id: "mistral-ai",
    name: "Mistral AI",
    category: "AI & LLM",
    summary: "Open-weight LLM provider. French-engineered minimalism, purple-toned.",
    swatches: ["#FA520F", "#FFD900", "#FFA110", "#FFFAEB"],
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "Backend & Data",
    summary: "Product analytics. Playful hedgehog branding, developer-friendly dark UI.",
    swatches: ["#FDFDF8", "#F54E00", "#1E1F23", "#BFC1B7"],
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "Backend & Data",
    summary: "Error monitoring. Dark dashboard, data-dense, pink-purple accent.",
    swatches: ["#1F1633", "#150F23", "#C2EF4E", "#79628C"],
  },
  {
    id: "cloudflare-kumo",
    name: "Cloudflare Kumo",
    category: "Developer Tools",
    summary:
      "A compact, semantic component language for modern web applications: layered neutral surfaces, precise Inter typography, accessible controls, automatic light/dark color roles, and task-appropriate chart palettes.",
    swatches: ["#FFFFFF", "#F6821F", "#FC574A", "#F8A054"],
  },
  {
    id: "framer",
    name: "Framer",
    category: "Design & Creative",
    summary: "Website builder. Bold black and blue, motion-first, design-forward.",
    swatches: ["#000000", "#0099FF", "#FFFFFF", "#A6A6A6"],
  },
  {
    id: "webflow",
    name: "Webflow",
    category: "Design & Creative",
    summary: "Visual web builder. Blue-accented, polished marketing site aesthetic.",
    swatches: ["#146EF5", "#080808", "#7A3DFF", "#ED52CB"],
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "E-Commerce & Retail",
    summary: "E-commerce platform. Dark-first cinematic, neon green accent, ultra-light type.",
    swatches: ["#02090A", "#061A1C", "#102620", "#36F4A4"],
  },
  {
    id: "slack",
    name: "Slack",
    category: "Productivity & SaaS",
    summary:
      "Workplace communication platform. Aubergine-primary, multi-accent logo palette, light surfaces with dark sidebar, warm and approachable.",
    swatches: ["#4A154B", "#FFFFFF", "#F8F8F8", "#350D36"],
  },
  {
    id: "uber",
    name: "Uber",
    category: "Media & Consumer",
    summary: "Mobility platform. Bold black and white, tight type, urban energy.",
    swatches: ["#000000", "#FFFFFF", "#E2E2E2", "#F3F3F3"],
  },
  {
    id: "nike",
    name: "Nike",
    category: "E-Commerce & Retail",
    summary: "Athletic retail. Monochrome UI, massive uppercase type, full-bleed photography.",
    swatches: ["#111111", "#000000", "#FFFFFF", "#FAFAFA"],
  },
  {
    id: "tesla",
    name: "Tesla",
    category: "Automotive",
    summary: "Electric automotive. Radical subtraction, full-viewport photography, near-zero UI.",
    swatches: ["#3E6AE1", "#FFFFFF", "#F4F4F4", "#171A20"],
  },
  {
    id: "ibm",
    name: "IBM",
    category: "Media & Consumer",
    summary: "Enterprise technology. Carbon design system, structured blue palette.",
    swatches: ["#FFFFFF", "#161616", "#0F62FE", "#F4F4F4"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "Backend & Data",
    summary: "Document database. Green leaf branding, developer documentation focus.",
    swatches: ["#001E2B", "#00ED64", "#B8C4C2", "#00684A"],
  },
  {
    id: "resend",
    name: "Resend",
    category: "Productivity & SaaS",
    summary: "Email API. Minimal dark theme, monospace accents.",
    swatches: ["#000000", "#F0F0F0", "#FFFFFF", "#FF5900"],
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "Productivity & SaaS",
    summary: "Automation platform. Warm orange, friendly illustration-driven.",
    swatches: ["#FFFEFB", "#201515", "#FF4F00", "#C5C0B1"],
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "Design & Creative",
    summary: "Spreadsheet-database hybrid. Colorful, friendly, structured data aesthetic.",
    swatches: ["#181D26", "#1B61C9", "#FFFFFF", "#006400"],
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Productivity & SaaS",
    summary: "Customer messaging. Friendly blue palette, conversational UI patterns.",
    swatches: ["#FAF9F6", "#111111", "#FF5600", "#DEDBD6"],
  },
  {
    id: "miro",
    name: "Miro",
    category: "Design & Creative",
    summary: "Visual collaboration. Bright yellow accent, infinite canvas aesthetic.",
    swatches: ["#1C1C1E", "#5B76FE", "#00B473", "#FFFFFF"],
  },
  {
    id: "coinbase",
    name: "Coinbase",
    category: "Fintech & Crypto",
    summary: "Crypto exchange. Clean blue identity, trust-focused, institutional feel.",
    swatches: ["#0052FF", "#578BFA", "#0A0B0D", "#282B31"],
  },
  {
    id: "revolut",
    name: "Revolut",
    category: "Fintech & Crypto",
    summary: "Digital banking. Sleek dark interface, gradient cards, fintech precision.",
    swatches: ["#E23B4A", "#EC7E00", "#00A87E", "#494FDF"],
  },
  {
    id: "wise",
    name: "Wise",
    category: "Fintech & Crypto",
    summary: "Money transfer. Bright green accent, friendly and clear.",
    swatches: ["#0E0F0C", "#9FE870", "#163300", "#E2F6D5"],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "AI & LLM",
    summary: "AI voice platform. Dark cinematic UI, audio-waveform aesthetics.",
    swatches: ["#FFFFFF", "#F5F5F5", "#F5F2EF", "#777169"],
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "AI & LLM",
    summary: "Enterprise AI platform. Vibrant gradients, data-rich dashboard aesthetic.",
    swatches: ["#D9D9DD", "#E5E7EB", "#1863DC", "#000000"],
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    category: "AI & LLM",
    summary:
      "Conversational AI search engine. Deep-dark canvas, sharp typography, single violet accent, dense information hierarchy.",
    swatches: ["#0F0F10", "#19191A", "#232325", "#2E2E30"],
  },
  {
    id: "warp",
    name: "Warp",
    category: "Developer Tools",
    summary: "Modern terminal. Dark IDE-like interface, block-based command UI.",
    swatches: ["#FAF9F6", "#353534", "#868584", "#AFAEAC"],
  },
];
